= CF Workshop Microservices Lab

== Intro

This lab demonstrates the benefits of deploying microservice applications to Cloud Foundry and building those applications with the Spring framework. It will also get you more confortable working with the CF CLI.

The lab starts with a monolithic v1 version of the cities-app, which is a Angular.js/Spring Boot/Spring Web/Spring Data application that provides a simple UI for searching for cities that are stored in a relational database. It's pushed as a single CF app.

It's a perfectly nice app, and does a lot with a little code thanks to the use of Spring Boot, Web and Data projects. But seeing the wisdom of microservices, you decide it's time to refactor this app into two tiers

* a microservice tier that  implements the core cities CRUD operations and provides a REST API via http://projects.spring.io/spring-data-rest/[Spring Data Rest]
* a UI tier that calls this REST API and uses a CF user provided service to reference the connection parameters from the CF environment

You'll deploy the refactoried v2 cities-app as two separate apps (an app for each tier), giving you the flexibility to update and scale each tier independently.

Then the lab will then take you through a blue/green (or A/B) deployment to route 'production' traffic from your v1 app to your v2 app and demonstrate how the CF router simplifies application upgrades.

== Instructions

=== Login to PWS

Using the CF CLI, target and login to your run.pivotal.io account

[source,bash]
----
$ cf api api.run.pivotal.io
$ cf login
----

Delete the PCF-demo app to make the memory available for this lab

[source,bash]
----
$ cf delete -r pcfdemo
----

=== Deploy the v1 Monolithic Cities App

Clone or download the cities-monolithic app:

[source,bash]
----
$ git clone https://github.com/jholmes2001/cities-monolithic
----

Create the SQL database used to store the city data

[source,bash]
----
$ cf create-service cleardb spark cities-db
----

Validate that the service is created

[source,bash]
----
$ cf services
Getting services...

name             service       plan     bound apps
cities-db        cleardb       spark
----

Before pushing the app, take a look at the manifest.yml to see that 
		
* The host name (the URL prefix) is being set to cities-app-${random-word}. This will be the 'production URL' we reference in the blue/green deployment exercise.
* The app will bind to the cities-db you created earlier
* An environment variable VERSION is being set to CITIES_APP_1_0

[source,bash]
----	
$ cd cities-monolithic
$ cat manifest.yml
---
applications:
- name: cities-monolithic
  memory: 512M
  instances: 1
  path: build/libs/cities-monolithic.jar
  timeout: 180
  services:
  - cities-db
  host: cities-app-${random-word}
  env:
    SPRING_PROFILES_ACTIVE: cloud
    VERSION: CITIES_APP_1_0
----

Deploy the app

[source,bash]
----
$ cf push
----

Validate that the app is working by opening in a browser the URL listed by 'cf apps'

[source,bash]
----	
$ cf apps
…
name                requested state   instances   memory   disk   urls   
cities-monolithic   started           1/1         512M     1G     cities-app-unplodding-tetrarch.cfapps.io 
----

Now that your v1 app is working, take a look at the https://github.com/jholmes2001/cities-monolithic/blob/master/src/main/java/com/example/cities/controller/CitiesController.java[CityController] to see that it is directly invoking a https://github.com/jholmes2001/cities-monolithic/blob/master/src/main/java/com/example/cities/repositories/CityRepository.java[CityRepository] object, based on Spring Data, and the UI and data tier are deployed as a single monolithic unit.

=== Deploy the v2 Microservices App

Now it's time to deploy the v2 microservice version of the app. Clone or download the v2 app:

[source,bash]
----
$ cd <your workspace root>
$ git clone https://github.com/jholmes2001/spring-boot-cities
$ cd spring-boot-cities
----

Under this folder are 3 subfolders

* cities-service - the microservice app that exposes a REST API from the https://github.com/jholmes2001/spring-boot-cities/blob/master/cities-service/src/main/java/com/example/cities/repositories/CityRepository.java[CityRepository] class via a few simple RestResource annotations
* cities-ui - the UI app that connects to the microservice
* cities-client - client API used by cities-ui to connect to cities-service microservice, leveraging http://projects.spring.io/spring-cloud/[Spring Cloud] and https://github.com/Netflix/feign[Netflix Feign]
		
Check out the https://github.com/jholmes2001/spring-boot-cities[app docs] for a thorough coverage of the application design.

First we'll deploy the cites-service microservice app, which defines in the manifest.yml the 'host' as 'cities-service-${random-word}' and 'cities-db' as a service the app will bind to (i.e. it will bind to the same db we created for the v1 app).

[source,bash]
----
$ cd cities-service
$ cf push
----

Use 'cf apps' to determine the URL to reference the cities microservice. 

* We'll refer to this URL as YOUR_CITIES_SERVICE_URL below, and in the example output below YOUR_CITIES_SERVICE_URL=cities-service-nonterminable-runback.cfapps.io
	
[source,bash]
----
$ cf apps
…
name                requested state   instances   memory   disk   urls   
cities-service      started           1/1         512M     1G     cities-service-nonterminable-runback.cfapps.io 
----

Validate that the REST endpoints are working for this service using curl

* Note: for Windows users, download cURL using following instructions below

** http://callejoabel.blogspot.com/2013/09/making-curl-work-on-windows-7.html

[source,bash]
----			
$ curl -i YOUR_CITIES_SERVICE_URL/cities
$ curl -i YOUR_CITIES_SERVICE_URL/cities/search
$ curl -i YOUR_CITIES_SERVICE_URL/cities/search/nameContains?q=TEMPLE
$ curl -i YOUR_CITIES_SERVICE_URL/cities/8291
----

Create the cities-ws http://docs.pivotal.io/pivotalcf/devguide/services/user-provided.html[user provided service] that will store the cities-service connection parameters in the CF environment and make them available to the cities-ui app.

* NOTE: YOU MUST USE 'http://' before the YOUR_CITIES_SERVICE_URL! (https will not work)
* Don't forget to substitute your specific URL for YOUR_CITIES_SERVICE_URL

[source,bash]
----
$ cf create-user-provided-service cities-ws -p '{ "uri": "http://YOUR_CITIES_SERVICE_URL", "tag": "cities" }'
----

Validate the user provided service was created

[source,bash]
----
$ cf services
…
name             service         plan     bound apps   
cities-db        cleardb         spark    cities-monolithic, cities-service   
cities-ws        user-provided        
----

Before pushing the cities-ui app that connects to the cities-service microservice app, take a look at the cities-ui manifest.yml to see

* The app will bind to the cities-ws user provided service you just created
* The app will use cities-ui-${random-word} as the host (URL prefix)
* The app sets the VERSION environment variable to CITIES_APP_2_0

[source,bash]
----	
$ cd ../cities-ui
$ cat manifest.yml
---
applications:
- name: cities-ui
  memory: 512M
  instances: 1
  path: build/libs/cities-ui.jar
  services: [ cities-ws ]
  host: cities-ui-${random-word}
  env:
    SPRING_PROFILES_ACTIVE: cloud
    VERSION: CITIES_APP_2_0
----

Now deploy the cities-ui app 

[source,bash]
----	
$ cf push
----

Test that the app works by opening the cities-ui URL that is displayed by the 'cf apps' command. The UI should look the same as the v1 version, but it's of course getting the data via REST from the cities-service microservice.

Now that the cities-ui app is pushed and bound to the cities-ws service, you can use 'cf env' to validate the cities-service URL/URI it found in the environment.

[source,bash]
----	
$ cf env cities-ui
…
System-Provided:
{
  "VCAP_SERVICES": {
    "user-provided": [
      {
        "credentials": {
          "tag": "cities",
          "uri": "http://cities-service-nonterminable-runback.cfapps.io"
        },
        "label": "user-provided",
        "name": "cities-ws",
        "syslog_drain_url": "",
        "tags": []
      }
    ]
  }
}

User-Provided:
SPRING_PROFILES_ACTIVE: cloud
VERSION: CITIES_APP_2_0
)
----

At this point, you are prepared to reap the benefits of having a separate microservice that can be scaled and deployed independently of the UI tier. However, let's hold off on scaling until we're done with the blue/green deployment and can delete the v1 app (a PWS trial has a 2G limit, which we're not too far from at this point).

=== Perform Blue/Green Deployment

Now you're ready to perform a blue/green deployment. First we'll list our existing routing table:

[source,bash]
----
$ cf routes
…
host                                      domain      apps
cities-service-nonterminable-runback      cfapps.io   cities-service
cities-app-unplodding-tetrarch            cfapps.io   cities-monolithic
cities-ui-slumberous-arroyo               cfapps.io   cities-ui
----

The host and domain listed for the cities-monolithic app is the 'production' URL that we want to remain constant during the upgrade process so our users are not aware that the v1 app is being replaced by the v2 app.

We can validate that that this URL is referencing our v1 app by using the /cities/version request mapping to retrieve the VERSION environment variable

* Substitute your cities-monolithic URL below

[source,bash]
----
$ curl cities-app-unplodding-tetrarch.cfapps.io/cities/version
CITIES_APP_1_0
----

We can also validate the version of the cities-ui route, which is our v2 app

[source,bash]
----
$ curl cities-ui-slumberous-arroyo.cfapps.io/cities/version
CITIES_APP_2_0
----

In a more realistic blue/green deployment scenario, we'd have a cluster of multiple v1 app instances deployed already, but since we're short on memory (i.e. PWS trial 2G limit), we'll stick with our single instance ''cluster''.

Now we add our v2 'canary' to the v1 cluster my mapping the v1 'production' route to the cities-ui app (i.e. the -n parameter is the host for cities-monolithic returned by 'cf routes')

[source,bash]
----
$ cf map-route cities-ui cfapps.io -n cities-app-unplodding-tetrarch
----

Now if we repeatedly visit our production URL, we'll see the CF router is load balancing requests between the v1 and v2 apps.

[source,bash]
----
$ curl cities-app-unplodding-tetrarch.cfapps.io/cities/version
CITIES_APP_1_0
$ curl cities-app-unplodding-tetrarch.cfapps.io/cities/version
CITIES_APP_2_0
----

Another look at our routes shows both apps are now mapped to the production route as expected

[source,bash]
----
$ cf routes
…
host                                      domain      apps
cities-service-nonterminable-runback      cfapps.io   cities-service
cities-app-unplodding-tetrarch            cfapps.io   cities-monolithic,cities-ui
cities-ui-slumberous-arroyo               cfapps.io   cities-ui
----

After performing some validation that our v2 canary is working as expected, we're ready to retire the v1 app instances from the cluster by unmapping the production route to the v1 cities-monolithic app, using 'cf unmap'

[source,bash]
----
$ cf unmap-route cities-monolithic cfapps.io -n cities-app-unplodding-tetrarch.cfapps.io
----

Then test our production URL to see all traffic is going to v2:

[source,bash]
----
$ curl cities-app-unplodding-tetrarch.cfapps.io/cities/version
CITIES_APP_2_0
$ curl cities-app-unplodding-tetrarch.cfapps.io/cities/version
CITIES_APP_2_0
…
----

At this point we can delete our v1 app

[source,bash]
----
$ cf delete cities-monolithic
----

Congratulations, you have successfully performed a blue/green deployment, and done so without massive amounts of custom scripting.

Finally, with a bit of spare memory, you can try scaling both tiers of your v2 microservice app.

[source,bash]
----
$ cf scale cities-ui -i 2
$ cf scale cities-service -i 2
$ cf apps
----

UI request will now be load balanced across two instances of cities-ui, and REST requests made by cities-ui to cities-service will be automatically load balanced as well. Wow, microservices, Spring and CF are a great combination!

